### ISSUE TITLE
support "comma first" option as provided by js beautifier

### ISSUE THREAD

**Issue by jiangyang** [jdc0589/jsformat-atom#55]
As the title says...the option is supported by jsbeautifier

> -C, --comma-first                 Put commas at the beginning of new line instead of end

I'd be glad to take any workaround to supply opts to js beautifier in addition to those exposed on the atom ui, too. Thanks.

**Comment by ilanbiala** [comment]
@jiangyang the config needs to modified to support this https://github.com/jdc0589/jsformat-atom/blob/master/lib/config.coffee. Can you put together a PR?
