### ISSUE TITLE
meteor-api package incompatibility

### ISSUE THREAD

**Issue by luclu** [jdc0589/jsformat-atom#57]
When the package meteor-api is installed, its syntaxt-highlighting 'javascript (meteor)' breaks the .js recognition of jsformat.
No show stopper, because syntaxt-highlighting can bechanged, but not intuitive at all. ;)

**Comment by ilanbiala** [comment]
@luclu is there a fix for this? I don't work with meteor-api, so I wouldn't really know what's going on.

**Comment by luclu** [comment]
@ilanbiala skimming through the code I guess this is the place to change:
``` if (!(grammar is 'JSON' or grammar is 'JavaScript'))``` @ https://github.com/jdc0589/jsformat-atom/blob/master/lib/format.coffee#L32
meteor-api uses ```JavaScript (Meteor)```

I'll will try to create a pull-request with a fix after testing tomorrow.
