### ISSUE TITLE
JSLint happy settings doesn't work

### ISSUE THREAD

**Issue by mrsoto** [jdc0589/jsformat-atom#70]
Hello.
I've 2 plugns: jsfrmat-atom and jslint [1]

both packages looks to be incompatible. I saw the jsformat has jslint happy default to false (in the documentation), I check it but formatting isn't jslint compatible.

Is there a way to use this plugging and lint sources at the same time?

1: https://atom.io/packages/jslint

**Comment by ilanbiala** [comment]
@mrsoto we haven't tested against other packages, so all I can say is that this package formats according to specific settings and using it with any other formatting plugin may cause inconsistencies in formatting.

**Comment by mrsoto** [comment]
Hello and thanks for your rapid response. 
Global ident setting is one of mayor problem. I was expected that jslint happy on  produce a format more compatible with jslint as a macro/super setting. Isn't it?

**Comment by ilanbiala** [comment]
@mrsoto our settings are separate, so they aren't guaranteed to work with any others.
